### ISSUE TITLE
请问我在开源AOSP Android9代码中想通过robox那种采用外部显卡的形式启动Android9，合入了kbox中的patch（除了你们显卡直通的patch），在系统启动Zygote启动systemserver时报错如下，请问你们遇到过这个错误吗？希望能提供些解决思路...万分感谢

### ISSUE THREAD

**Issue by maxingrong1213** [kunpengcompute/Kbox#34]
01-14 11:08:11.355     1     1 I /init   : starting service 'zygote'...
01-14 11:08:11.355     1     1 I /init   : starting service 'vendor.camera-provider-2-4'...
01-14 11:08:11.356 53548 53548 I /init   : Created socket '/dev/socket/zygote', mode 660, user 0, group 1000
01-14 11:08:11.356     1     1 I /init   : starting service 'vendor.sensors-hal-1-0'...
01-14 11:08:11.374 53549 53549 I android.hardware.camera.provider@2.4-service: Camera provider Service is starting.
01-14 11:08:11.375 53549 53549 D vndksupport: Loading /vendor/lib/hw/android.hardware.camera.provider@2.4-impl.so from current namespace instead of sphal namespace.
01-14 11:08:11.385 53549 53549 E CamProvider@2.4-impl: Could not load camera HAL module: -2 (No such file or directory)
01-14 11:08:11.385 53549 53549 E CamProvider@2.4-impl: HIDL_FETCH_ICameraProvider: camera provider init failed!
01-14 11:08:11.386 53549 53549 E android.hardware.camera.provider@2.4-service: Could not get passthrough implementation for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0.
01-14 11:08:11.387     1     1 I /init   : Service 'vendor.camera-provider-2-4' (pid 53549) exited with status 1
01-14 11:08:11.387     1     1 I /init   : Sending signal 9 to service 'vendor.camera-provider-2-4' (pid 53549) process group...
01-14 11:08:11.388 53550 53550 D vndksupport: Loading /vendor/lib64/hw/android.hardware.sensors@1.0-impl.so from current namespace instead of sphal namespace.
01-14 11:08:11.389 53550 53550 E /vendor/bin/hw/android.hardware.sensors@1.0-service: Couldn't load sensors module (Unknown error -2147483648)
01-14 11:08:11.389 53550 53550 E android.hardware.sensors@1.0-service: Could not get passthrough implementation for android.hardware.sensors@1.0::ISensors/default.
01-14 11:08:11.390     1     1 I /init   : Service 'vendor.sensors-hal-1-0' (pid 53550) exited with status 1
01-14 11:08:11.390     1     1 I /init   : Sending signal 9 to service 'vendor.sensors-hal-1-0' (pid 53550) process group...
01-14 11:08:11.534 53548 53548 D AndroidRuntime: >>>>>> START com.android.internal.os.ZygoteInit uid 0 <<<<<<
01-14 11:08:11.538 53548 53548 I zygote64: option[0]=-Xzygote
01-14 11:08:11.538 53548 53548 I zygote64: option[1]=-Xusetombstonedtraces
01-14 11:08:11.538 53548 53548 I zygote64: option[2]=exit
01-14 11:08:11.538 53548 53548 I zygote64: option[3]=vfprintf
01-14 11:08:11.538 53548 53548 I zygote64: option[4]=sensitiveThread
01-14 11:08:11.538 53548 53548 I zygote64: option[5]=-verbose:gc
01-14 11:08:11.538 53548 53548 I zygote64: option[6]=-Xms5m
01-14 11:08:11.538 53548 53548 I zygote64: option[7]=-Xmx256m
01-14 11:08:11.538 53548 53548 I zygote64: option[8]=-XX:HeapGrowthLimit=48m
01-14 11:08:11.538 53548 53548 I zygote64: option[9]=-XX:HeapMinFree=512k
01-14 11:08:11.539 53548 53548 I zygote64: option[10]=-XX:HeapMaxFree=2m
01-14 11:08:11.539 53548 53548 I zygote64: option[11]=-XX:HeapTargetUtilization=0.75
01-14 11:08:11.539 53548 53548 I zygote64: option[12]=-Xusejit:true
01-14 11:08:11.539 53548 53548 I zygote64: option[13]=-Xjitsaveprofilinginfo
01-14 11:08:11.539 53548 53548 I zygote64: option[14]=-XjdwpOptions:suspend=n,server=y
01-14 11:08:11.539 53548 53548 I zygote64: option[15]=-XjdwpProvider:default
01-14 11:08:11.539 53548 53548 I zygote64: option[16]=-Xlockprofthreshold:500
01-14 11:08:11.539 53548 53548 I zygote64: option[17]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[18]=--runtime-arg
01-14 11:08:11.539 53548 53548 I zygote64: option[19]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[20]=-Xms64m
01-14 11:08:11.539 53548 53548 I zygote64: option[21]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[22]=--runtime-arg
01-14 11:08:11.539 53548 53548 I zygote64: option[23]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[24]=-Xmx64m
01-14 11:08:11.539 53548 53548 I zygote64: option[25]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[26]=--profile-file=/system/etc/boot-image.prof
01-14 11:08:11.539 53548 53548 I zygote64: option[27]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[28]=--compiler-filter=speed-profile
01-14 11:08:11.539 53548 53548 I zygote64: option[29]=-Xcompiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[30]=--runtime-arg
01-14 11:08:11.539 53548 53548 I zygote64: option[31]=-Xcompiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[32]=-Xms64m
01-14 11:08:11.539 53548 53548 I zygote64: option[33]=-Xcompiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[34]=--runtime-arg
01-14 11:08:11.539 53548 53548 I zygote64: option[35]=-Xcompiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[36]=-Xmx512m
01-14 11:08:11.539 53548 53548 I zygote64: option[37]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[38]=--instruction-set-variant=generic
01-14 11:08:11.539 53548 53548 I zygote64: option[39]=-Xcompiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[40]=--instruction-set-variant=generic
01-14 11:08:11.539 53548 53548 I zygote64: option[41]=-Ximage-compiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[42]=--instruction-set-features=default
01-14 11:08:11.539 53548 53548 I zygote64: option[43]=-Xcompiler-option
01-14 11:08:11.539 53548 53548 I zygote64: option[44]=--instruction-set-features=default
01-14 11:08:11.539 53548 53548 I zygote64: option[45]=-Duser.locale=zh-CN
01-14 11:08:11.539 53548 53548 I zygote64: option[46]=--cpu-abilist=arm64-v8a
01-14 11:08:11.539 53548 53548 I zygote64: option[47]=-Xfingerprint:Android/dockdroid_arm64_for_KunPeng916/arm64:9/PPR2.180905.006.A1/dockdroid01042228:userdebug/test-keys
01-14 11:08:11.540 53548 53548 W zygote64: Incomplete boot detected. Pruning dalvik cache
01-14 11:08:11.547 53548 53548 I zygote64: VerifyImage: /system/bin/patchoat --input-image-location=/system/framework/boot.art --output-image-directory=/data/dalvik-cache/arm64 --instruction-set=arm64 --verify
01-14 11:08:11.578 53551 53551 E patchoat: Unable to open relocated image file  /data/dalvik-cache/arm64/system@framework@boot.art
01-14 11:08:11.581 53548 53548 W zygote64: Failed execv(/system/bin/patchoat --input-image-location=/system/framework/boot.art --output-image-directory=/data/dalvik-cache/arm64 --instruction-set=arm64 --verify) because non-0 exit status Preemptively pruning the dalvik cache.
01-14 11:08:11.581 53548 53548 I zygote64: Pruning dalvik-cache since we are relocating an image and will need to recompile
01-14 11:08:11.582 53548 53548 I zygote64: RelocateImage: /system/bin/patchoat --input-image-location=/system/framework/boot.art --output-image-directory=/data/dalvik-cache/arm64 --instruction-set=arm64 --base-offset-delta=-8187904
01-14 11:08:11.713    85    85 W ServiceManagement: Waited one second for android.hardware.gatekeeper@1.0::IGatekeeper/default. Waiting another...
01-14 11:08:11.713    71    71 W ServiceManagement: Waited one second for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0. Waiting another...
01-14 11:08:11.812 53548 53548 D Zygote  : begin preload
01-14 11:08:11.812 53548 53548 I Zygote  : Installing ICU cache reference pinning...
01-14 11:08:11.812 53548 53548 I Zygote  : Preloading ICU data...
01-14 11:08:11.816 53548 53548 D Zygote64Timing: BeginIcuCachePinning took to complete: 4ms
01-14 11:08:11.816 53548 53548 I Zygote  : Preloading classes...
01-14 11:08:11.824 53548 53548 I PackageBackwardCompatibility: Loaded android.content.pm.OrgApacheHttpLegacyUpdater
01-14 11:08:11.824 53548 53548 I PackageBackwardCompatibility: Could not find android.content.pm.AndroidTestBaseUpdater, ignoring
01-14 11:08:11.935 53548 53548 E ActivityRecognitionHardware: activity_recognition HAL is deprecated. class_init is effectively a no-op
01-14 11:08:11.962 53548 53548 I zygote64: Thread[1,tid=53548,Native,Thread*=0xffff13e14c00,peer=0x12fc0000,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
01-14 11:08:11.962 53548 53548 D MtpDeviceJNI: register_android_mtp_MtpDevice
01-14 11:08:11.962 53548 53548 I zygote64: Thread[1,tid=53548,Native,Thread*=0xffff13e14c00,peer=0x12fc0000,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
01-14 11:08:11.962 53548 53548 I zygote64: Thread[1,tid=53548,Native,Thread*=0xffff13e14c00,peer=0x12fc0000,"main"] recursive attempt to load library "/system/lib64/libmedia_jni.so"
01-14 11:08:12.031 53548 53548 I Zygote  : ...preloaded 6535 classes in 215ms.
01-14 11:08:12.031 53548 53548 I zygote64: VMRuntime.preloadDexCaches starting
01-14 11:08:12.051 53548 53548 I zygote64: VMRuntime.preloadDexCaches strings total=338941 before=12310 after=12310
01-14 11:08:12.051 53548 53548 I zygote64: VMRuntime.preloadDexCaches types total=31344 before=7821 after=7822
01-14 11:08:12.051 53548 53548 I zygote64: VMRuntime.preloadDexCaches fields total=140700 before=9178 after=9178
01-14 11:08:12.051 53548 53548 I zygote64: VMRuntime.preloadDexCaches methods total=247703 before=12780 after=12780
01-14 11:08:12.051 53548 53548 I zygote64: VMRuntime.preloadDexCaches finished
01-14 11:08:12.051 53548 53548 D Zygote64Timing: PreloadClasses took to complete: 235ms
01-14 11:08:12.099 53548 53548 I Zygote  : Preloading resources...
01-14 11:08:12.103 53548 53548 W Resources: Preloaded drawable resource #0x1080265 (android:drawable/dialog_background_material) that varies with configuration!!
01-14 11:08:12.111 53548 53548 I Zygote  : ...preloaded 64 resources in 13ms.
01-14 11:08:12.114 53548 53548 I Zygote  : ...preloaded 41 resources in 2ms.
01-14 11:08:12.114 53548 53548 D Zygote64Timing: PreloadResources took to complete: 62ms
01-14 11:08:12.114 53548 53548 D vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
01-14 11:08:12.115 53548 53548 D libEGL  : Emulator has host GPU support, qemu.gles is set to 1.
01-14 11:08:12.115 53548 53548 D vndksupport: Loading /vendor/lib64/egl/libGLES_emulation.so from current namespace instead of sphal namespace.
01-14 11:08:12.115 53548 53548 E libEGL  : load_driver(/vendor/lib64/egl/libGLES_emulation.so): dlopen failed: library "/vendor/lib64/egl/libGLES_emulation.so" not found
01-14 11:08:12.115 53548 53548 D vndksupport: Loading /vendor/lib64/egl/libEGL_emulation.so from current namespace instead of sphal namespace.
01-14 11:08:12.117 53548 53548 D libEGL  : loaded /vendor/lib64/egl/libEGL_emulation.so
01-14 11:08:12.118 53548 53548 D vndksupport: Loading /vendor/lib64/egl/libGLESv1_CM_emulation.so from current namespace instead of sphal namespace.
01-14 11:08:12.118 53548 53548 D libEGL  : loaded /vendor/lib64/egl/libGLESv1_CM_emulation.so
01-14 11:08:12.127 53548 53548 D vndksupport: Loading /vendor/lib64/egl/libGLESv2_emulation.so from current namespace instead of sphal namespace.
01-14 11:08:12.128 53548 53548 D libEGL  : loaded /vendor/lib64/egl/libGLESv2_emulation.so
01-14 11:08:12.138 53548 53548 I Zygote  : Preloading shared libraries...
01-14 11:08:12.142 53548 53548 I Zygote  : Uninstalled ICU cache reference pinning...
01-14 11:08:12.143 53548 53548 I Zygote  : Installed AndroidKeyStoreProvider in 0ms.
01-14 11:08:12.147 53548 53548 I Zygote  : Warmed up JCA providers in 5ms.
01-14 11:08:12.147 53548 53548 D Zygote  : end preload
01-14 11:08:12.147 53548 53548 D Zygote64Timing: ZygotePreload took to complete: 335ms
01-14 11:08:12.165 53548 53548 I zygote64: Explicit concurrent copying GC freed 42838(2MB) AllocSpace objects, 138(2MB) LOS objects, 49% free, 2MB/4MB, paused 63us total 17.634ms
01-14 11:08:12.178 53548 53548 I zygote64: Explicit concurrent copying GC freed 1680(97KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 2MB/4MB, paused 46us total 12.871ms
01-14 11:08:12.178 53548 53548 D Zygote64Timing: PostZygoteInitGC took to complete: 31ms
01-14 11:08:12.178 53548 53548 D Zygote64Timing: ZygoteInit took to complete: 366ms
01-14 11:08:12.209 53548 53548 F zygote64: jni_internal.cc:616] JNI FatalError called: (system_server) Unsupported st_mode 4480
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558] Runtime aborting...
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558] Dumping all threads without appropriate locks held: thread list lock mutator lock
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558] All threads:
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558] DALVIK THREADS (1):
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558] "main" prio=5 tid=1 Runnable
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   | group="" sCount=0 dsCount=0 flags=0 obj=0x744db770 self=0xffff13e14c00
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   | sysTid=53548 nice=0 cgrp=kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podbfc8cab7_be5c_47ed_8b26_6f3acd1df98e.slice/docker-25b1fa16b6e3ddb3b725f611ce3178b2f478de0435c89f21431a02416949c650.scope sched=0/0 handle=0xffff999eb548
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   | state=R schedstat=( 627591160 9951680 48 ) utm=48 stm=13 core=9 HZ=100
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   | stack=0xfffff5102000-0xfffff5104000 stackSize=8MB
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   | held mutexes= "abort lock" "mutator lock"(shared held)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #00 pc 00000000003c1684  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+220)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #01 pc 000000000048ec40  /system/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+352)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #02 pc 00000000004a87cc  /system/lib64/libart.so (art::DumpCheckpoint::Run(art::Thread*)+844)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #03 pc 00000000004a15d8  /system/lib64/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+484)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #04 pc 00000000004a0a68  /system/lib64/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+1036)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #05 pc 0000000000463dec  /system/lib64/libart.so (art::Runtime::Abort(char const*)+388)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #06 pc 0000000000008cd4  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #07 pc 000000000032ce68  /system/lib64/libart.so (art::JNI::FatalError(_JNIEnv*, char const*)+196)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #08 pc 000000000018dc64  /system/lib64/libandroid_runtime.so (_ZZN12_GLOBAL__N_123ForkAndSpecializeCommonEP7_JNIEnvjjP10_jintArrayiP13_jobjectArraylliP8_jstringS7_bS3_S3_bS7_S7_ENK3$_0clERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEE+164)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #09 pc 000000000018d834  /system/lib64/libandroid_runtime.so ((anonymous namespace)::ForkAndSpecializeCommon(_JNIEnv*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long, long, int, _jstring*, _jstring*, bool, _jintArray*, _jintArray*, bool, _jstring*, _jstring*)+5320)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #10 pc 000000000018baf8  /system/lib64/libandroid_runtime.so (android::com_android_internal_os_Zygote_nativeForkSystemServer(_JNIEnv*, _jclass*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long, long)+100)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   at com.android.internal.os.Zygote.nativeForkSystemServer(Native method)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   at com.android.internal.os.ZygoteInit.forkSystemServer(ZygoteInit.java:712)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:833)
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558] "main" prio=5 tid=1 Native
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   | sysTid=53548 nice=0 cgrp=kubepods.slice/kubepods-burstable.slice/kubepods-burstable-podbfc8cab7_be5c_47ed_8b26_6f3acd1df98e.slice/docker-25b1fa16b6e3ddb3b725f611ce3178b2f478de0435c89f21431a02416949c650.scope sched=0/0 handle=0xffff999eb548
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   | stack=0xfffff5102000-0xfffff5104000 stackSize=8MB
01-14 11:08:12.298 53548 53548 F zygote64: runtime.cc:558]   native: #04 pc 0000000000008cd4  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #06 pc 000000000018dc64  /system/lib64/libandroid_runtime.so (_ZZN12_GLOBAL__N_123ForkAndSpecializeCommonEP7_JNIEnvjjP10_jintArrayiP13_jobjectArraylliP8_jstringS7_bS3_S3_bS7_S7_ENK3$_0clERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEE+164)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #08 pc 000000000018baf8  /system/lib64/libandroid_runtime.so (android::com_android_internal_os_Zygote_nativeForkSystemServer(_JNIEnv*, _jclass*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long, long)+100)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #11 pc 0000000000beab5c  /system/framework/arm64/boot-framework.oat (offset 3cd000) (com.android.internal.os.ZygoteInit.main+2876)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #13 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #14 pc 000000000045c840  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #15 pc 000000000045c4a0  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #16 pc 0000000000361b60  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   native: #19 pc 000000000000219c  /system/bin/app_process64 (main+1200)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   at com.android.internal.os.Zygote.nativeForkSystemServer(Native method)
01-14 11:08:12.299 53548 53548 F zygote64: runtime.cc:558]   at com.android.internal.os.Zygote.forkSystemServer(Zygote.java:190)
01-14 11:08:12.299 53548 53548 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 53548 (main), pid 53548 (main)
01-14 11:08:12.320 53565 53565 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
01-14 11:08:12.323    87    87 I /system/bin/tombstoned: received crash request for pid 53548
01-14 11:08:12.323 53565 53565 I crash_dump64: performing dump of process 53548 (target tid = 53548)
01-14 11:08:12.327 53565 53565 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-14 11:08:12.327 53565 53565 F DEBUG   : Build fingerprint: 'Android/dockdroid_arm64_for_KunPeng916/arm64:9/PPR2.180905.006.A1/dockdroid01042228:userdebug/test-keys'
01-14 11:08:12.327 53565 53565 F DEBUG   : Revision: '0'
01-14 11:08:12.327 53565 53565 F DEBUG   : ABI: 'arm64'
01-14 11:08:12.327 53565 53565 F DEBUG   : pid: 53548, tid: 53548, name: main  >>> zygote64 <<<
01-14 11:08:12.327 53565 53565 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-14 11:08:12.327 53565 53565 F DEBUG   : Abort message: 'jni_internal.cc:616] JNI FatalError called: (system_server) Unsupported st_mode 4480'
01-14 11:08:12.327 53565 53565 F DEBUG   :     x0  0000000000000000  x1  000000000000d12c  x2  0000000000000006  x3  0000000000000008
01-14 11:08:12.327 53565 53565 F DEBUG   :     x4  0000ffff13f28c40  x5  0000ffff13f28c40  x6  0000ffff13f28c40  x7  0000ffff13f27c00
01-14 11:08:12.327 53565 53565 F DEBUG   :     x8  0000000000000083  x9  190d7dea4a0c18b3  x10 0000000000000000  x11 fffffffc7ffffbdf
01-14 11:08:12.327 53565 53565 F DEBUG   :     x12 0000000000000001  x13 0000ffff13f27840  x14 0000000000000000  x15 ffffffffffffffff
01-14 11:08:12.327 53565 53565 F DEBUG   :     x16 0000ffff98ef02c0  x17 0000ffff98e2e058  x18 0000000000000001  x19 000000000000d12c
01-14 11:08:12.327 53565 53565 F DEBUG   :     x20 000000000000d12c  x21 0000ffff13f0e2c0  x22 0000ffff13d08763  x23 0000ffff13d02a63
01-14 11:08:12.327 53565 53565 F DEBUG   :     x24 0000ffff13d02917  x25 0000000000000001  x26 0000ffff999eb5e0  x27 0000000000000000
01-14 11:08:12.327 53565 53565 F DEBUG   :     x28 0000ffff13f0e2a0  x29 0000fffff58fd510
01-14 11:08:12.327 53565 53565 F DEBUG   :     sp  0000fffff58fd4d0  lr  0000ffff98e22b84  pc  0000ffff98e22bac
01-14 11:08:12.397 53565 53565 F DEBUG   :
01-14 11:08:12.397 53565 53565 F DEBUG   : backtrace:
01-14 11:08:12.397 53565 53565 F DEBUG   :     #00 pc 0000000000021bac  /system/lib64/libc.so (abort+116)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #01 pc 0000000000464114  /system/lib64/libart.so (art::Runtime::Abort(char const*)+1196)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #02 pc 0000000000008cd4  /system/lib64/libbase.so (android::base::LogMessage::~LogMessage()+724)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #03 pc 000000000032ce68  /system/lib64/libart.so (art::JNI::FatalError(_JNIEnv*, char const*)+196)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #04 pc 000000000018dc64  /system/lib64/libandroid_runtime.so (_ZZN12_GLOBAL__N_123ForkAndSpecializeCommonEP7_JNIEnvjjP10_jintArrayiP13_jobjectArraylliP8_jstringS7_bS3_S3_bS7_S7_ENK3$_0clERKNSt3__112basic_stringIcNS9_11char_traitsIcEENS9_9allocatorIcEEEE+164)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #05 pc 000000000018d834  /system/lib64/libandroid_runtime.so ((anonymous namespace)::ForkAndSpecializeCommon(_JNIEnv*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long, long, int, _jstring*, _jstring*, bool, _jintArray*, _jintArray*, bool, _jstring*, _jstring*)+5320)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #06 pc 000000000018baf8  /system/lib64/libandroid_runtime.so (android::com_android_internal_os_Zygote_nativeForkSystemServer(_JNIEnv*, _jclass*, unsigned int, unsigned int, _jintArray*, int, _jobjectArray*, long, long)+100)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #07 pc 00000000003fffbc  /system/framework/arm64/boot-framework.oat (offset 0x3cd000) (com.android.internal.os.Zygote.nativeForkSystemServer+252)
01-14 11:08:12.397 53565 53565 F DEBUG   :     #08 pc 0000000000be9784  /system/framework/arm64/boot-framework.oat (offset 0x3cd000) (com.android.internal.os.ZygoteInit.forkSystemServer+1348)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #09 pc 0000000000beab5c  /system/framework/arm64/boot-framework.oat (offset 0x3cd000) (com.android.internal.os.ZygoteInit.main+2876)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #10 pc 0000000000554c4c  /system/lib64/libart.so (art_quick_invoke_static_stub+604)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #11 pc 00000000000cf6e8  /system/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+232)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #12 pc 000000000045c840  /system/lib64/libart.so (art::(anonymous namespace)::InvokeWithArgArray(art::ScopedObjectAccessAlreadyRunnable const&, art::ArtMethod*, art::(anonymous namespace)::ArgArray*, art::JValue*, char const*)+104)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #13 pc 000000000045c4a0  /system/lib64/libart.so (art::InvokeWithVarArgs(art::ScopedObjectAccessAlreadyRunnable const&, _jobject*, _jmethodID*, std::__va_list)+424)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #14 pc 0000000000361b60  /system/lib64/libart.so (art::JNI::CallStaticVoidMethodV(_JNIEnv*, _jclass*, _jmethodID*, std::__va_list)+652)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #15 pc 00000000000b1ad4  /system/lib64/libandroid_runtime.so (_JNIEnv::CallStaticVoidMethod(_jclass*, _jmethodID*, ...)+120)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #16 pc 00000000000b4458  /system/lib64/libandroid_runtime.so (android::AndroidRuntime::start(char const*, android::Vector<android::String8> const&, bool)+756)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #17 pc 000000000000219c  /system/bin/app_process64 (main+1200)
01-14 11:08:12.398 53565 53565 F DEBUG   :     #18 pc 00000000000ad070  /system/lib64/libc.so (__libc_init+88)
01-14 11:08:12.713    85    85 W ServiceManagement: Waited one second for android.hardware.gatekeeper@1.0::IGatekeeper/default. Waiting another...
01-14 11:08:12.713    71    71 W ServiceManagement: Waited one second for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0. Waiting another...
01-14 11:08:12.717 53565 53565 E crash_dump64: unable to connect to activity manager: No such file or directory
01-14 11:08:12.718    87    87 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_46
01-14 11:08:12.720 53548 53548 F libc    : failed to restore dumpable: Invalid argument
01-14 11:08:12.721     1     1 I /init   : Untracked pid 53565 exited with status 0
01-14 11:08:12.726     1     1 I /init   : Untracked pid 53567 exited with status 0
01-14 11:08:12.732     1     1 I /init   : Service 'zygote' (pid 53548) exited with status 1
01-14 11:08:12.732     1     1 I /init   : Sending signal 9 to service 'zygote' (pid 53548) process group...
01-14 11:08:13.713    85    85 W ServiceManagement: Waited one second for android.hardware.gatekeeper@1.0::IGatekeeper/default. Waiting another...
01-14 11:08:13.713    71    71 W ServiceManagement: Waited one second for android.hardware.camera.provider@2.4::ICameraProvider/legacy/0. Waiting another...

**Comment by maxingrong1213** [comment]
已解决
